/* ============================================================
   Multicolor — default data (Georgian).
   Typed port of the handoff's data.js seed catalogue.
   ============================================================ */

import type { MulticolorData } from "./types";

export const MC_DATA: MulticolorData = {
  v: 3,

  /* ---------------- brands ---------------- */
  brands: [
    {
      id: "sobsan",
      name: "Sobsan",
      country: "თურქეთი",
      tint: "#2f4bc7",
      tagline: "საღებავები და ლაქები 1974 წლიდან",
      story:
        "Sobsan-ი თურქეთის ერთ-ერთი უმსხვილესი საღებავების მწარმოებელია. წყალემულსიური და სილიკონის საღებავები, ლაქები და გრუნტები — ევროპული სტანდარტის რეცეპტურით და სტაბილური ხარისხით.",
    },
    {
      id: "premium",
      name: "Premium",
      country: "თურქეთი",
      tint: "#b3541e",
      tagline: "სამონტაჟო ქაფი და ჰერმეტიკები",
      story:
        "Premium-ის ქაფი, სილიკონი და MS-პოლიმერული წებოები პროფესიონალი მემონტაჟეების პირველი არჩევანია — სტაბილური გამოსავალი, ზუსტი დოზირება და მდგრადობა ნებისმიერ სეზონზე.",
    },
    {
      id: "starbond",
      name: "Starbond",
      country: "თურქეთი",
      tint: "#1e7a52",
      tagline: "წებო და ბიტუმის იზოლაცია",
      story:
        "Starbond-ი სპეციალიზებულია სამშენებლო წებოებსა და ბიტუმის ჰიდროიზოლაციაზე. PVA-დან ეპოქსიდამდე — შეკავშირება, რომელსაც ენდობი.",
    },
    {
      id: "bauer",
      name: "Bauer",
      country: "საბერძნეთი",
      tint: "#3a3f8f",
      tagline: "სამშენებლო ქიმია საბერძნეთიდან",
      story:
        "Bauer-ის ცემენტის ჰიდროიზოლაცია, ფუგები და გრუნტები ათწლეულებია გამოიყენება ხმელთაშუა ზღვის რეგიონის რთულ კლიმატში — ტენი, მზე და მარილიანი ჰაერი მისთვის ჩვეული გარემოა.",
    },
    {
      id: "teirani",
      name: "Teirani",
      country: "ირანი",
      tint: "#8f2d3a",
      tagline: "აეროზოლის საღებავები RAL პალიტრით",
      story:
        "Teirani-ის აეროზოლები სრულ RAL პალიტრას ფარავს — სითბომედეგი, ფლუორესცენტული და ანტიკოროზიული სერიებით. თანაბარი დაფარვა პირველივე შესხურებიდან.",
    },
    {
      id: "asmako",
      name: "Asmako",
      country: "თურქეთი",
      tint: "#46698c",
      tagline: "ლენტები, ფუნჯები, ლილვაკები",
      story:
        "Asmako ამზადებს სამღებრო ინსტრუმენტს — ფუნჯებს, ლილვაკებსა და ლენტებს, რომელთა ხარისხსაც ნახატზე ხედავ: თანაბარი კვალი, მინიმალური წვეთვა, სუფთა კიდეები.",
    },
    {
      id: "stargil",
      name: "Stargil",
      country: "თურქეთი",
      tint: "#7a5a2f",
      tagline: "გამხსნელები და 24 ფერის კოლორანტი",
      story:
        "Stargil-ის გამხსნელები და კოლორანტები საღებავის სამუშაოს ქიმიური საფუძველია — სუფთა შემადგენლობა, ზუსტი მარკირება და სტაბილური ფერი პარტიიდან პარტიამდე.",
    },
    {
      id: "proian",
      name: "Proian",
      country: "ჩინეთი",
      tint: "#444a52",
      tagline: "ბურღები, თავაკები, ხელსაწყოები",
      story:
        "Proian-ის საბურღი და საჭრელი ინსტრუმენტი პროფესიონალური კლასისაა — HSS-G ფოლადიდან SDS-MAX-მდე, ქარხნული კალიბრაციით და ხანგრძლივი რესურსით.",
    },
  ],

  /* ---------------- categories ---------------- */
  categories: [
    {
      id: "paints-we",
      name: "წყალემულსიური საღებავები",
      group: "paint",
      facets: ["size", "color", "surface"],
      order: 1,
      sub: ["ინტერიერის", "ფასადის", "სილიკონის"],
    },
    {
      id: "lacquers",
      name: "ლაქები",
      group: "paint",
      facets: ["size", "color", "surface"],
      order: 2,
      sub: ["იატაკის", "კარ-ფანჯრის", "ფერადი", "ნიტრო"],
    },
    { id: "primers", name: "გრუნტი", group: "paint", facets: ["size", "surface"], order: 3 },
    {
      id: "aerosols",
      name: "აეროზოლის საღებავები",
      group: "paint",
      facets: ["color", "surface"],
      order: 4,
      sub: ["RAL სერია", "სითბომედეგი", "ფლუორესცენტული", "ანტიკოროზიული"],
    },
    { id: "solvents", name: "გამხსნელები და კოლორი", group: "paint", facets: ["size", "color"], order: 5 },
    {
      id: "waterproof",
      name: "ჰიდროიზოლაცია",
      group: "chem",
      facets: ["size", "surface"],
      order: 6,
      sub: ["სახურავის", "ბიტუმის", "სააბაზანოს", "PU"],
    },
    {
      id: "adhesives",
      name: "წებო",
      group: "chem",
      facets: ["size", "surface"],
      order: 7,
      sub: ["PVA", "ეპოქსიდი", "თხევადი ლურსმნები", "მყისიერი"],
    },
    { id: "foam", name: "სამონტაჟო ქაფი", group: "chem", facets: ["size"], order: 8 },
    { id: "sealants", name: "სილიკონი და ჰერმეტიკი", group: "chem", facets: ["size", "color", "surface"], order: 9 },
    { id: "grout", name: "ფუგა", group: "chem", facets: ["size", "color"], order: 10 },
    {
      id: "tapes",
      name: "ლენტები",
      group: "tool",
      facets: ["size", "color"],
      order: 11,
      sub: ["მალარის", "საიზოლაციო", "ფოლგის", "ბუტილის"],
    },
    { id: "brushes", name: "ფუნჯები", group: "tool", facets: ["size"], order: 12 },
    { id: "rollers", name: "ლილვაკები და აქსესუარები", group: "tool", facets: ["size"], order: 13 },
    {
      id: "drills",
      name: "ბურღები",
      group: "tool",
      facets: ["size", "surface"],
      order: 14,
      sub: ["HSS-G", "კობალტი", "SDS-Plus", "SDS-MAX", "TCT"],
    },
    { id: "bits", name: "თავაკები", group: "tool", facets: ["size"], order: 15 },
    { id: "tools", name: "ხელსაწყოები", group: "tool", facets: [], order: 16 },
  ],

  catGroups: [
    { id: "paint", name: "საღებავები და ლაქები" },
    { id: "chem", name: "სამშენებლო ქიმია" },
    { id: "tool", name: "ინსტრუმენტი და აქსესუარები" },
  ],

  surfaces: [
    { id: "interior", name: "ინტერიერი" },
    { id: "facade", name: "ფასადი" },
    { id: "floor", name: "იატაკი" },
    { id: "roof", name: "სახურავი" },
    { id: "bathroom", name: "სააბაზანო" },
    { id: "metal", name: "ლითონი" },
    { id: "wood", name: "ხე" },
    { id: "concrete", name: "ბეტონი" },
  ],

  /* ---------------- products ---------------- */
  products: [
    {
      id: "sobplastik-int",
      brand: "sobsan",
      cat: "paints-we",
      name: "SOBPLASTIK — ინტერიერის წყალემულსიური საღებავი",
      desc: "მქრქალი, თეთრად მშრალი ინტერიერის საღებავი კედლისა და ჭერისთვის. იშლება თანაბრად, სუნი მინიმალურია.",
      sizes: [
        { l: "3.5კგ", p: 24.9, s: 64 },
        { l: "5კგ", p: 32.5, s: 41 },
        { l: "10კგ", p: 59.9, s: 23 },
        { l: "25კგ", p: 129.0, s: 12 },
      ],
      colors: [
        { n: "თეთრი", h: "#f5f4ef" },
        { n: "კრემისფერი", h: "#eee4d0" },
        { n: "ღია ნაცარი", h: "#cccecb" },
        { n: "ცისფერი", h: "#bfd6e4" },
        { n: "მიტკალი", h: "#e7d8c4" },
      ],
      specs: { surface: ["interior"], coverage: "1კგ — 4–6 მ²", drying: "2–4 სთ", base: "წყალდისპერსიული" },
      tags: [],
      featured: true,
    },
    {
      id: "sobsil-facade",
      brand: "sobsan",
      cat: "paints-we",
      name: "SOBSİL — ფასადის სილიკონის საღებავი",
      desc: "სილიკონ-მოდიფიცირებული ფასადის საღებავი. წყალს იგერიებს, ორთქლს ატარებს — ფასადი „სუნთქავს“.",
      sizes: [
        { l: "10ლტ", p: 148.0, s: 18 },
        { l: "15ლტ", p: 209.0, s: 9 },
      ],
      colors: [
        { n: "თეთრი", h: "#f4f3ee" },
        { n: "ქვიშისფერი", h: "#ddd0b4" },
        { n: "ღია რუხი", h: "#c5c6c2" },
      ],
      specs: { surface: ["facade", "concrete"], coverage: "1ლტ — 5–7 მ²", drying: "4–6 სთ", base: "სილიკონის ემულსია" },
      tags: ["new"],
      featured: true,
    },
    {
      id: "sobplastik-silk",
      brand: "sobsan",
      cat: "paints-we",
      name: "SOBPLASTIK SILK — სარეცხი მატი საღებავი",
      desc: "ინტერიერის საღებავი გაზრდილი ცვეთამედეგობით — სამზარეულო, დერეფანი, საბავშვო. ირეცხება ღრუბლით.",
      sizes: [
        { l: "2.5კგ", p: 27.9, s: 35 },
        { l: "10კგ", p: 89.0, s: 14 },
      ],
      colors: [
        { n: "თეთრი", h: "#f5f4f0" },
        { n: "თბილი თეთრი", h: "#f1ebdd" },
        { n: "ფისტა", h: "#d4ddc2" },
        { n: "ლავანდა", h: "#d4cfe0" },
      ],
      specs: { surface: ["interior"], coverage: "1კგ — 5–7 მ²", drying: "2 სთ", base: "აკრილის დისპერსია" },
      tags: ["sale"],
      salePct: 15,
    },
    {
      id: "sobdur-bath",
      brand: "sobsan",
      cat: "paints-we",
      name: "SOBDUR — სველი წერტილების საღებავი",
      desc: "ანტიბაქტერიული დანამატით, ობის საწინააღმდეგო. სააბაზანოსა და სამზარეულოსთვის.",
      sizes: [
        { l: "2.5კგ", p: 31.5, s: 27 },
        { l: "10კგ", p: 99.0, s: 8 },
      ],
      colors: [{ n: "თეთრი", h: "#f6f6f3" }],
      specs: { surface: ["interior", "bathroom"], coverage: "1კგ — 5 მ²", drying: "3 სთ", base: "აკრილის დისპერსია" },
      tags: [],
    },
    {
      id: "lak-floor-pu",
      brand: "sobsan",
      cat: "lacquers",
      name: "იატაკის ლაქი პოლიურეთანული",
      desc: "ორკომპონენტიანი PU ლაქი პარკეტისა და ხის იატაკისთვის. მაღალი ცვეთამედეგობა, ნახევრად პრიალა.",
      sizes: [
        { l: "0.75ლტ", p: 28.9, s: 30 },
        { l: "2.5ლტ", p: 84.0, s: 16 },
      ],
      colors: [],
      specs: { surface: ["floor", "wood"], coverage: "1ლტ — 10–12 მ²", drying: "24 სთ", base: "პოლიურეთანი" },
      tags: [],
      featured: true,
    },
    {
      id: "lak-door",
      brand: "sobsan",
      cat: "lacquers",
      name: "კარ-ფანჯრის ალკიდური ლაქი",
      desc: "ფერადი ლაქი ხის ზედაპირისთვის — კარი, ფანჯარა, ავეჯი. UV ფილტრით.",
      sizes: [
        { l: "0.75ლტ", p: 19.9, s: 44 },
        { l: "2.5ლტ", p: 56.0, s: 19 },
      ],
      colors: [
        { n: "უფერო", h: "#dcc9a4" },
        { n: "მუხა", h: "#8b5a2b" },
        { n: "კაკალი", h: "#5c4033" },
        { n: "მაჰაგონი", h: "#6f2e25" },
        { n: "ვენგე", h: "#3c2f2a" },
      ],
      specs: { surface: ["wood", "interior"], coverage: "1ლტ — 12 მ²", drying: "12 სთ", base: "ალკიდი" },
      tags: ["sale"],
      salePct: 20,
    },
    {
      id: "lak-nitro",
      brand: "sobsan",
      cat: "lacquers",
      name: "ნიტრო ლაქი NC სწრაფშრობადი",
      desc: "ნიტროცელულოზის ლაქი ავეჯისა და დეტალებისთვის. შრება 30 წუთში, იშლება პისტოლეტითაც.",
      sizes: [
        { l: "1ლტ", p: 16.5, s: 52 },
        { l: "5ლტ", p: 72.0, s: 11 },
      ],
      colors: [],
      specs: { surface: ["wood"], coverage: "1ლტ — 8–10 მ²", drying: "30 წთ", base: "ნიტროცელულოზა" },
      tags: [],
    },
    {
      id: "primer-deep",
      brand: "sobsan",
      cat: "primers",
      name: "ღრმა შეღწევადი გრუნტი კონცენტრატი",
      desc: "ამაგრებს ფხვიერ ზედაპირს და ამცირებს საღებავის ხარჯს. ზავდება წყლით 1:1-მდე.",
      sizes: [
        { l: "1ლტ", p: 8.9, s: 80 },
        { l: "5ლტ", p: 34.0, s: 33 },
        { l: "10ლტ", p: 59.0, s: 15 },
      ],
      colors: [],
      specs: {
        surface: ["interior", "facade", "concrete"],
        coverage: "1ლტ — 8–10 მ²",
        drying: "2 სთ",
        base: "აკრილის დისპერსია",
      },
      tags: ["new"],
      featured: true,
    },
    {
      id: "primer-beton",
      brand: "bauer",
      cat: "primers",
      name: "ბეტონ-კონტაქტი ადჰეზიური გრუნტი",
      desc: "კვარცის მინარევით — გლუვ ბეტონზე ბათქაში და ფილა მყარად ეჭიდება.",
      sizes: [
        { l: "5კგ", p: 42.0, s: 21 },
        { l: "20კგ", p: 139.0, s: 7 },
      ],
      colors: [],
      specs: { surface: ["concrete", "interior"], coverage: "1კგ — 3–4 მ²", drying: "3 სთ", base: "აკრილი + კვარცი" },
      tags: [],
    },
    {
      id: "hydro-cem2k",
      brand: "bauer",
      cat: "waterproof",
      name: "ორკომპონენტიანი ცემენტის ჰიდროიზოლაცია",
      desc: "ელასტიური ცემენტ-პოლიმერული შემადგენლობა აბაზანის, აუზისა და საძირკვლისთვის.",
      sizes: [{ l: "25კგ", p: 119.0, s: 26 }],
      colors: [],
      specs: {
        surface: ["bathroom", "concrete", "roof"],
        coverage: "1კგ — 0.7 მ² (2 ფენა)",
        drying: "24 სთ",
        base: "ცემენტ-პოლიმერი",
      },
      tags: [],
      featured: true,
    },
    {
      id: "hydro-bitum",
      brand: "starbond",
      cat: "waterproof",
      name: "ბიტუმის მასტიკა სახურავისთვის",
      desc: "ცივი წასმის ბიტუმის მასტიკა — სახურავის, საძირკვლისა და მილების იზოლაცია.",
      sizes: [
        { l: "5კგ", p: 27.0, s: 38 },
        { l: "17კგ", p: 79.0, s: 14 },
      ],
      colors: [],
      specs: { surface: ["roof", "concrete"], coverage: "1კგ — 1 მ²", drying: "24 სთ", base: "ბიტუმი" },
      tags: ["sale"],
      salePct: 10,
    },
    {
      id: "hydro-pu",
      brand: "bauer",
      cat: "waterproof",
      name: "PU თხევადი მემბრანა ჰიდროიზოლაციისთვის",
      desc: "ერთკომპონენტიანი პოლიურეთანის მემბრანა ტერასისა და ბრტყელი სახურავისთვის. UV-მდგრადი.",
      sizes: [
        { l: "6კგ", p: 145.0, s: 9 },
        { l: "25კგ", p: 520.0, s: 4 },
      ],
      colors: [
        { n: "თეთრი", h: "#f2f2ee" },
        { n: "რუხი", h: "#9a9d9c" },
      ],
      specs: { surface: ["roof", "concrete"], coverage: "1.5კგ — 1 მ²", drying: "12 სთ", base: "პოლიურეთანი" },
      tags: ["new"],
    },
    {
      id: "glue-pva",
      brand: "starbond",
      cat: "adhesives",
      name: "PVA წებო უნივერსალური D2",
      desc: "ხის, ქაღალდისა და სამშენებლო ნარევების დანამატად. გამჭვირვალედ შრება.",
      sizes: [
        { l: "0.9კგ", p: 6.5, s: 92 },
        { l: "2.5კგ", p: 15.9, s: 40 },
        { l: "10კგ", p: 54.0, s: 13 },
      ],
      colors: [],
      specs: { surface: ["wood", "interior"], drying: "24 სთ", base: "PVA დისპერსია" },
      tags: [],
    },
    {
      id: "glue-msnails",
      brand: "premium",
      cat: "adhesives",
      name: "თხევადი ლურსმნები MS-პოლიმერი",
      desc: "უნივერსალური სამონტაჟო წებო სველ ზედაპირზეც. ცვლის ლურსმანსა და ჭანჭიკს მსუბუქ მონტაჟში.",
      sizes: [{ l: "290მლ", p: 13.9, s: 67 }],
      colors: [
        { n: "თეთრი", h: "#f4f4f1" },
        { n: "რუხი", h: "#a8a9a5" },
      ],
      specs: { surface: ["interior", "concrete", "wood", "metal"], drying: "24 სთ", base: "MS პოლიმერი" },
      tags: [],
      featured: true,
    },
    {
      id: "glue-epoxy",
      brand: "starbond",
      cat: "adhesives",
      name: "ეპოქსიდური წებო ორკომპონენტიანი",
      desc: "ლითონის, ქვისა და კერამიკის ძლიერი შეწებება. სამუშაო დრო — 5 წუთი.",
      sizes: [
        { l: "24მლ", p: 7.9, s: 75 },
        { l: "250გრ", p: 24.0, s: 22 },
      ],
      colors: [],
      specs: { surface: ["metal", "concrete"], drying: "5 წთ (სრული — 24 სთ)", base: "ეპოქსიდი" },
      tags: [],
    },
    {
      id: "glue-cyano",
      brand: "premium",
      cat: "adhesives",
      name: "მყისიერი წებო ციანოაკრილატი",
      desc: "წამიერი შეკავშირება — რეზინა, პლასტმასი, კერამიკა. ზუსტი დოზატორით.",
      sizes: [
        { l: "20გრ", p: 4.5, s: 120 },
        { l: "50გრ", p: 8.9, s: 48 },
      ],
      colors: [],
      specs: { drying: "10 წმ", base: "ციანოაკრილატი" },
      tags: ["sale"],
      salePct: 25,
    },
    {
      id: "foam-pro65",
      brand: "premium",
      cat: "foam",
      name: "სამონტაჟო ქაფი პროფესიონალური 65L",
      desc: "პისტოლეტის ქაფი გაზრდილი გამოსავლით — 65 ლიტრამდე. მკვრივი სტრუქტურა, მინიმალური მეორადი გაფართოება.",
      sizes: [{ l: "850მლ", p: 14.5, s: 96 }],
      colors: [],
      specs: { coverage: "გამოსავალი — 65ლტ-მდე", drying: "სრული — 24 სთ", base: "პოლიურეთანი" },
      tags: [],
      featured: true,
    },
    {
      id: "foam-winter",
      brand: "premium",
      cat: "foam",
      name: "ზამთრის სამონტაჟო ქაფი −18°C",
      desc: "მუშაობს ყინვაშიც — სტაბილური გამოსავალი დაბალ ტემპერატურაზე.",
      sizes: [{ l: "750მლ", p: 13.5, s: 54 }],
      colors: [],
      specs: { coverage: "გამოსავალი — 45ლტ", drying: "24 სთ", base: "პოლიურეთანი" },
      tags: ["new"],
    },
    {
      id: "foam-cleaner",
      brand: "premium",
      cat: "foam",
      name: "ქაფის გამწმენდი სითხე",
      desc: "ასუფთავებს პისტოლეტსა და ახალ ქაფს. აუცილებელია პისტოლეტის რესურსისთვის.",
      sizes: [{ l: "500მლ", p: 7.5, s: 88 }],
      colors: [],
      specs: { base: "აცეტონის ბაზა" },
      tags: [],
    },
    {
      id: "seal-sanitary",
      brand: "premium",
      cat: "sealants",
      name: "სანიტარული სილიკონი ანტიბაქტერიული",
      desc: "ობის საწინააღმდეგო დანამატით — აბაზანა, სანტექნიკა, სამზარეულო.",
      sizes: [{ l: "280მლ", p: 9.9, s: 110 }],
      colors: [
        { n: "გამჭვირვალე", h: "#e8e8e4" },
        { n: "თეთრი", h: "#f6f6f3" },
      ],
      specs: { surface: ["bathroom"], drying: "ფენა — 20 წთ", base: "აცეტოქსი სილიკონი" },
      tags: [],
    },
    {
      id: "seal-universal",
      brand: "premium",
      cat: "sealants",
      name: "უნივერსალური სილიკონის ჰერმეტიკი",
      desc: "მინა, ალუმინი, კერამიკა — ელასტიური ნაკერი შიდა და გარე სამუშაოებზე.",
      sizes: [{ l: "280მლ", p: 8.5, s: 95 }],
      colors: [
        { n: "თეთრი", h: "#f5f5f2" },
        { n: "გამჭვირვალე", h: "#e6e6e2" },
        { n: "რუხი", h: "#a3a4a0" },
        { n: "ყავისფერი", h: "#6b4a35" },
        { n: "შავი", h: "#2c2c2a" },
      ],
      specs: { surface: ["interior", "facade", "metal"], drying: "ფენა — 25 წთ", base: "სილიკონი" },
      tags: [],
    },
    {
      id: "seal-acrylic",
      brand: "premium",
      cat: "sealants",
      name: "აკრილის ჰერმეტიკი დასაღებავი",
      desc: "ბზარებისა და ნაკერების ამოსავსებად — შეღებვადია ნებისმიერი საღებავით.",
      sizes: [{ l: "310მლ", p: 6.9, s: 73 }],
      colors: [{ n: "თეთრი", h: "#f5f5f1" }],
      specs: { surface: ["interior"], drying: "1 სთ", base: "აკრილი" },
      tags: ["sale"],
      salePct: 10,
    },
    {
      id: "aero-ral",
      brand: "teirani",
      cat: "aerosols",
      name: "აეროზოლის საღებავი RAL სერია",
      desc: "სწრაფშრობადი აკრილის ემალი RAL პალიტრით — ლითონი, ხე, პლასტმასი.",
      sizes: [{ l: "400მლ", p: 8.9, s: 140 }],
      colors: [
        { n: "შავი მქრქალი", h: "#17171a", ral: "RAL 9005" },
        { n: "თეთრი", h: "#f3f4f0", ral: "RAL 9010" },
        { n: "ალუბლისფერი", h: "#79242c", ral: "RAL 3003" },
        { n: "ზურმუხტი", h: "#1d6f50", ral: "RAL 6029" },
        { n: "სიგნალური ლურჯი", h: "#1f4796", ral: "RAL 5005" },
        { n: "ვერცხლისფერი", h: "#a6a8ab", ral: "RAL 9006" },
        { n: "ყვითელი", h: "#e8b714", ral: "RAL 1023" },
      ],
      specs: { surface: ["metal", "wood", "interior"], coverage: "400მლ — 1.5 მ²", drying: "15 წთ", base: "აკრილი" },
      tags: [],
      featured: true,
    },
    {
      id: "aero-heat",
      brand: "teirani",
      cat: "aerosols",
      name: "სითბომედეგი საღებავი +600°C",
      desc: "ბუხრის, მაყალისა და გამონაბოლქვი მილების შესაღებად. სილიკონის ფისის ბაზაზე.",
      sizes: [{ l: "400მლ", p: 12.9, s: 46 }],
      colors: [
        { n: "შავი", h: "#1d1d1f" },
        { n: "ვერცხლისფერი", h: "#aaacae" },
      ],
      specs: { surface: ["metal"], drying: "30 წთ", base: "სილიკონის ფისი" },
      tags: ["new"],
    },
    {
      id: "aero-rust",
      brand: "teirani",
      cat: "aerosols",
      name: "ჟანგის ნეიტრალიზატორი სპრეი",
      desc: "გარდაქმნის ჟანგს დამცავ ფენად — ღებვა შესაძლებელია უშუალოდ ზემოდან.",
      sizes: [{ l: "400მლ", p: 11.5, s: 39 }],
      colors: [],
      specs: { surface: ["metal"], drying: "2 სთ", base: "ფოსფატური" },
      tags: [],
    },
    {
      id: "aero-zinc",
      brand: "teirani",
      cat: "aerosols",
      name: "ცინკის სპრეი ანტიკოროზიული",
      desc: "ცივი მოთუთიება შედუღების ნაკერებსა და დაზიანებულ ადგილებზე. 96% ცინკი.",
      sizes: [{ l: "400მლ", p: 14.9, s: 31 }],
      colors: [{ n: "ცინკი მქრქალი", h: "#9fa4a6" }],
      specs: { surface: ["metal"], drying: "20 წთ", base: "ცინკი 96%" },
      tags: ["sale"],
      salePct: 15,
    },
    {
      id: "aero-fluo",
      brand: "teirani",
      cat: "aerosols",
      name: "ფლუორესცენტული სპრეი მარკირებისთვის",
      desc: "კაშკაშა სასიგნალო ფერები მშენებლობის მარკირებისა და დეკორისთვის.",
      sizes: [{ l: "400მლ", p: 9.9, s: 58 }],
      colors: [
        { n: "ყვითელი", h: "#f2e324" },
        { n: "ნარინჯისფერი", h: "#ff7b1c" },
        { n: "მწვანე", h: "#5ce03a" },
        { n: "ვარდისფერი", h: "#ff4fa0" },
      ],
      specs: { surface: ["concrete", "wood", "metal"], drying: "15 წთ", base: "აკრილი" },
      tags: [],
    },
    {
      id: "grout-epoxy",
      brand: "bauer",
      cat: "grout",
      name: "ეპოქსიდური ფუგა ორკომპონენტიანი",
      desc: "წყალმედეგი, ლაქებგამძლე ფუგა — აბაზანა, სამზარეულოს ფარდული, აუზი.",
      sizes: [
        { l: "2კგ", p: 49.0, s: 24 },
        { l: "5კგ", p: 109.0, s: 9 },
      ],
      colors: [
        { n: "თეთრი", h: "#f3f3f0" },
        { n: "ჟასმინი", h: "#ece2cb" },
        { n: "კარამელი", h: "#c89a6b" },
        { n: "ანთრაციტი", h: "#3b3d40" },
      ],
      specs: { surface: ["bathroom", "floor"], coverage: "ნაკერი 3მმ — ~0.4კგ/მ²", drying: "24 სთ", base: "ეპოქსიდი" },
      tags: [],
      featured: true,
    },
    {
      id: "grout-cement",
      brand: "bauer",
      cat: "grout",
      name: "ცემენტის ფუგა წყალმედეგი 1–8მმ",
      desc: "ელასტიფიცირებული ფუგა კედლისა და იატაკის ფილისთვის, 12 ფერში.",
      sizes: [
        { l: "2კგ", p: 11.9, s: 70 },
        { l: "5კგ", p: 26.0, s: 28 },
        { l: "20კგ", p: 92.0, s: 10 },
      ],
      colors: [
        { n: "თეთრი", h: "#f2f2ef" },
        { n: "ბაჰამა", h: "#e3d6bb" },
        { n: "ღია რუხი", h: "#c9cac6" },
        { n: "გრაფიტი", h: "#5a5c5e" },
        { n: "შოკოლადი", h: "#5f4231" },
      ],
      specs: {
        surface: ["bathroom", "floor", "interior"],
        coverage: "ნაკერი 3მმ — ~0.5კგ/მ²",
        drying: "24 სთ",
        base: "ცემენტ-პოლიმერი",
      },
      tags: [],
    },
    {
      id: "grout-cleaner",
      brand: "bauer",
      cat: "grout",
      name: "ცემენტის ნალექის მოსაშორებელი",
      desc: "მჟავური საწმენდი ფილაზე დარჩენილი ცემენტისა და ფუგის ნალექისთვის.",
      sizes: [
        { l: "1ლტ", p: 13.5, s: 42 },
        { l: "5ლტ", p: 49.0, s: 12 },
      ],
      colors: [],
      specs: { surface: ["floor", "bathroom"], base: "მჟავური" },
      tags: [],
    },
    {
      id: "tape-masking",
      brand: "asmako",
      cat: "tapes",
      name: "მალარის ლენტი 40მ",
      desc: "სუფთა კიდეების ლენტი ღებვისას — ძვრება კვალის გარეშე 48 საათამდე.",
      sizes: [
        { l: "25მმ", p: 2.9, s: 200 },
        { l: "38მმ", p: 3.9, s: 150 },
        { l: "48მმ", p: 4.9, s: 130 },
      ],
      colors: [],
      specs: { base: "ქაღალდი / აკრილის წებო" },
      tags: [],
    },
    {
      id: "tape-electric",
      brand: "asmako",
      cat: "tapes",
      name: "ელექტროიზოლაციის ლენტი PVC",
      desc: "ძაბვამედეგი PVC ლენტი 19მმ × 20მ. ცეცხლმედეგი შემადგენლობა.",
      sizes: [{ l: "19მმ", p: 1.9, s: 300 }],
      colors: [
        { n: "შავი", h: "#222224" },
        { n: "წითელი", h: "#b6252a" },
        { n: "ლურჯი", h: "#2049a8" },
        { n: "ყვითელი", h: "#e9c51c" },
      ],
      specs: { base: "PVC" },
      tags: ["sale"],
      salePct: 10,
    },
    {
      id: "tape-foil",
      brand: "asmako",
      cat: "tapes",
      name: "ალუმინის ფოლგის ლენტი 45მ",
      desc: "თბოამრეკლი ლენტი ვენტილაციისა და იზოლაციისთვის. მედეგია +120°C-მდე.",
      sizes: [
        { l: "48მმ", p: 8.9, s: 64 },
        { l: "72მმ", p: 12.5, s: 30 },
      ],
      colors: [],
      specs: { base: "ალუმინი 30მკმ" },
      tags: [],
    },
    {
      id: "tape-butyl",
      brand: "asmako",
      cat: "tapes",
      name: "ბუტილის ჰიდროიზოლაციის ლენტი 10მ",
      desc: "თვითწებვადი ბუტილის ლენტი — სახურავის ნაკერები, მილების შეერთება, ღარები.",
      sizes: [{ l: "10სმ", p: 24.0, s: 26 }],
      colors: [],
      specs: { surface: ["roof"], base: "ბუტილკაუჩუკი + ალუმინი" },
      tags: ["new"],
    },
    {
      id: "solv-646",
      brand: "stargil",
      cat: "solvents",
      name: "გამხსნელი 646",
      desc: "უნივერსალური გამხსნელი ნიტრო ემალისა და ლაქისთვის; ინსტრუმენტის გასაწმენდად.",
      sizes: [
        { l: "0.5ლტ", p: 4.5, s: 160 },
        { l: "1ლტ", p: 7.9, s: 95 },
        { l: "5ლტ", p: 34.0, s: 22 },
      ],
      colors: [],
      specs: { base: "კომბინირებული" },
      tags: [],
    },
    {
      id: "solv-white",
      brand: "stargil",
      cat: "solvents",
      name: "უაით-სპირიტი",
      desc: "ალკიდური საღებავებისა და ზეთოვანი ლაქების გასაზავებლად, ზედაპირის გასაწმენდად.",
      sizes: [
        { l: "0.5ლტ", p: 3.9, s: 180 },
        { l: "1ლტ", p: 6.9, s: 110 },
        { l: "5ლტ", p: 29.0, s: 25 },
      ],
      colors: [],
      specs: { base: "ნავთობის დისტილატი" },
      tags: [],
    },
    {
      id: "colorant-24",
      brand: "stargil",
      cat: "solvents",
      name: "უნივერსალური კოლორანტი — 24 ფერი",
      desc: "კონცენტრირებული პასტა წყალემულსიური საღებავის შესაფერად. 24 ფერი, ზუსტი დოზირება.",
      sizes: [{ l: "100მლ", p: 3.5, s: 240 }],
      colors: [
        { n: "ლიმონი", h: "#efd633" },
        { n: "ოხრა", h: "#c5912f" },
        { n: "აგური", h: "#b05a36" },
        { n: "ალისფერი", h: "#a72f3d" },
        { n: "იასამნისფერი", h: "#7d5ba6" },
        { n: "ულტრამარინი", h: "#2c4fa3" },
        { n: "ფირუზი", h: "#2e8f8a" },
        { n: "ხავსი", h: "#5d7a3a" },
      ],
      specs: { coverage: "100მლ — 10კგ საღებავზე", base: "პიგმენტური პასტა" },
      tags: [],
      featured: true,
    },
    {
      id: "brush-natural",
      brand: "asmako",
      cat: "brushes",
      name: "ფუნჯი ბუნებრივი ჯაგრისით",
      desc: "ალკიდური და ზეთოვანი საღებავისთვის — მკვრივი ბუნებრივი ჯაგარი, ხის ტარი.",
      sizes: [
        { l: "25მმ", p: 2.5, s: 140 },
        { l: "50მმ", p: 4.2, s: 120 },
        { l: "75მმ", p: 6.5, s: 80 },
        { l: "100მმ", p: 8.9, s: 60 },
      ],
      colors: [],
      specs: { base: "ბუნებრივი ჯაგარი" },
      tags: [],
    },
    {
      id: "brush-radiator",
      brand: "asmako",
      cat: "brushes",
      name: "რადიატორის ფუნჯი მოხრილი ტარით",
      desc: "ძნელად მისადგომი ადგილებისთვის — რადიატორი, მილების უკანა მხარე.",
      sizes: [{ l: "50მმ", p: 5.9, s: 45 }],
      colors: [],
      specs: { base: "სინთეზური ჯაგარი" },
      tags: [],
    },
    {
      id: "brush-set5",
      brand: "asmako",
      cat: "brushes",
      name: "ფუნჯების ნაკრები — 5 ცალი",
      desc: "20/30/40/50/63მმ — საბაზისო ნაკრები ნებისმიერი სამღებრო სამუშაოსთვის.",
      sizes: [{ l: "ნაკრები", p: 14.9, s: 55 }],
      colors: [],
      specs: { base: "შერეული ჯაგარი" },
      tags: ["sale"],
      salePct: 20,
    },
    {
      id: "roller-poly18",
      brand: "asmako",
      cat: "rollers",
      name: "ლილვაკი პოლიამიდის 18მმ ბეწვით",
      desc: "წყალემულსიური საღებავისთვის — იწოვს ბევრს, ტოვებს თანაბარ ფაქტურას.",
      sizes: [
        { l: "18სმ", p: 8.9, s: 90 },
        { l: "25სმ", p: 11.9, s: 70 },
      ],
      colors: [],
      specs: { base: "პოლიამიდი 18მმ" },
      tags: [],
      featured: true,
    },
    {
      id: "roller-refill",
      brand: "asmako",
      cat: "rollers",
      name: "ლილვაკის სათადარიგო ცილინდრი",
      desc: "სტანდარტული ბუდე — მოერგება Asmako-ს ყველა ჩარჩოს.",
      sizes: [
        { l: "18სმ", p: 4.9, s: 110 },
        { l: "25სმ", p: 6.5, s: 85 },
      ],
      colors: [],
      specs: { base: "პოლიესტერი" },
      tags: [],
    },
    {
      id: "roller-tray",
      brand: "asmako",
      cat: "rollers",
      name: "საღებავის კიუვეტა (აბაზანა)",
      desc: "მყარი პლასტმასის კიუვეტა საწურით — 25სმ და 32სმ ლილვაკისთვის.",
      sizes: [
        { l: "25სმ", p: 3.5, s: 130 },
        { l: "32სმ", p: 4.9, s: 95 },
      ],
      colors: [],
      specs: { base: "PP პლასტმასი" },
      tags: [],
    },
    {
      id: "roller-pole",
      brand: "asmako",
      cat: "rollers",
      name: "ტელესკოპური სახელური",
      desc: "ალუმინის ტელესკოპი ლილვაკისთვის — ჭერი და ფასადი კიბის გარეშე.",
      sizes: [
        { l: "1.5მ", p: 12.9, s: 40 },
        { l: "3მ", p: 21.0, s: 25 },
      ],
      colors: [],
      specs: { base: "ალუმინი" },
      tags: ["new"],
    },
    {
      id: "drill-hssg",
      brand: "proian",
      cat: "drills",
      name: "ბურღი ლითონის HSS-G",
      desc: "დაფქული HSS ბურღი 135° წვერით — ფოლადი, ფერადი ლითონი, პლასტმასი.",
      sizes: [
        { l: "4მმ", p: 2.5, s: 220 },
        { l: "6მმ", p: 4.2, s: 180 },
        { l: "8მმ", p: 6.9, s: 120 },
        { l: "10მმ", p: 9.5, s: 70 },
      ],
      colors: [],
      specs: { surface: ["metal"], base: "HSS-G ფოლადი" },
      tags: [],
    },
    {
      id: "drill-cobalt",
      brand: "proian",
      cat: "drills",
      name: "ბურღი კობალტის HSS-Co 5%",
      desc: "უჟანგავი და მაღალლეგირებული ფოლადისთვის — კობალტის შენადნობი ინარჩუნებს სიმკვეთრეს.",
      sizes: [
        { l: "4მმ", p: 4.9, s: 90 },
        { l: "6მმ", p: 7.9, s: 65 },
        { l: "8მმ", p: 12.5, s: 40 },
      ],
      colors: [],
      specs: { surface: ["metal"], base: "HSS-Co 5%" },
      tags: ["new"],
    },
    {
      id: "drill-sdsplus",
      brand: "proian",
      cat: "drills",
      name: "ბურღი SDS-Plus ბეტონისთვის",
      desc: "ოთხკიდიანი კარბიდის წვერი — ბეტონი, აგური, ქვა. პერფორატორისთვის.",
      sizes: [
        { l: "6×110მმ", p: 3.9, s: 150 },
        { l: "8×160მმ", p: 5.5, s: 110 },
        { l: "10×210მმ", p: 7.9, s: 75 },
        { l: "12×260მმ", p: 10.9, s: 45 },
      ],
      colors: [],
      specs: { surface: ["concrete"], base: "კარბიდი YG8" },
      tags: [],
      featured: true,
    },
    {
      id: "drill-sdsmax",
      brand: "proian",
      cat: "drills",
      name: "ბურღი SDS-MAX მძიმე სერიის",
      desc: "მძიმე პერფორატორებისთვის — რკინაბეტონის გაყვანილობის არხები და ანკერები.",
      sizes: [
        { l: "16×340მმ", p: 24.0, s: 28 },
        { l: "20×520მმ", p: 39.0, s: 14 },
      ],
      colors: [],
      specs: { surface: ["concrete"], base: "კარბიდი / 4 კიდე" },
      tags: [],
    },
    {
      id: "drill-tct",
      brand: "proian",
      cat: "drills",
      name: "ბურღი TCT კაფელისა და მინისთვის",
      desc: "შუბისებური კარბიდის წვერი — ფილა, კაფელი, მინა ბზარების გარეშე.",
      sizes: [
        { l: "6მმ", p: 4.5, s: 60 },
        { l: "8მმ", p: 5.9, s: 45 },
        { l: "10მმ", p: 7.5, s: 30 },
      ],
      colors: [],
      specs: { base: "TCT კარბიდი" },
      tags: [],
    },
    {
      id: "bit-ph2",
      brand: "proian",
      cat: "bits",
      name: "თავაკი PH2 ტორსიონული",
      desc: "S2 ფოლადის ტორსიონული ზონით — გაზრდილი რესურსი დარტყმით სამუშაოზე.",
      sizes: [
        { l: "25მმ", p: 1.5, s: 400 },
        { l: "50მმ", p: 2.5, s: 250 },
        { l: "90მმ", p: 3.9, s: 120 },
      ],
      colors: [],
      specs: { base: "S2 ფოლადი" },
      tags: [],
      featured: true,
    },
    {
      id: "bit-set32",
      brand: "proian",
      cat: "bits",
      name: "თავაკების ნაკრები PH/PZ/TX — 32 ცალი",
      desc: "მაგნიტური დამჭერით და კომპაქტური კასეტით. ყველაზე ხშირი 32 პროფილი.",
      sizes: [{ l: "32 ცალი", p: 29.0, s: 38 }],
      colors: [],
      specs: { base: "S2 ფოლადი" },
      tags: ["sale"],
      salePct: 15,
    },
    {
      id: "bit-gypsum",
      brand: "proian",
      cat: "bits",
      name: "თიხა-მუყაოს თავაკი შემზღუდველით",
      desc: "მაგნიტური თავაკი ღრმულის შემზღუდველით — ხრახნი ზუსტად მუყაოს დონეზე ჯდება.",
      sizes: [{ l: "25მმ", p: 4.9, s: 85 }],
      colors: [],
      specs: { base: "S2 + მაგნიტი" },
      tags: [],
    },
    {
      id: "tool-spatula",
      brand: "proian",
      cat: "tools",
      name: "შპაკლის დანა უჟანგავი ფოლადის",
      desc: "მოქნილი პირი, ორკომპონენტიანი ტარი — შპაკვლა და ზედაპირის მოსწორება.",
      sizes: [
        { l: "100მმ", p: 4.5, s: 75 },
        { l: "200მმ", p: 7.9, s: 50 },
        { l: "350მმ", p: 12.5, s: 30 },
      ],
      colors: [],
      specs: { base: "უჟანგავი ფოლადი" },
      tags: [],
    },
    {
      id: "tool-gun-sil",
      brand: "proian",
      cat: "tools",
      name: "სილიკონის პისტოლეტი გაძლიერებული",
      desc: "ჩარჩოიანი პისტოლეტი 1:12 გადაცემით — თანაბარი მიწოდება დაღლის გარეშე.",
      sizes: [{ l: "310მლ", p: 11.9, s: 42 }],
      colors: [],
      specs: { base: "ფოლადის ჩარჩო" },
      tags: [],
    },
    {
      id: "tool-gun-foam",
      brand: "proian",
      cat: "tools",
      name: "ქაფის პისტოლეტი ტეფლონის დაფარვით",
      desc: "ტეფლონის ადაპტერი და ნემსი — ადვილად იწმინდება, ზუსტი დოზირება.",
      sizes: [{ l: "სტანდარტი", p: 32.0, s: 26 }],
      colors: [],
      specs: { base: "ტეფლონი / ალუმინი" },
      tags: ["new"],
    },
  ],

  /* ---------------- promotions / hero ---------------- */
  hero: [
    {
      id: "h1",
      kicker: "სეზონის შეთავაზება",
      title: "ფასდაკლება საღებავებზე —20%-მდე",
      sub: "Sobsan-ის ინტერიერის სერია და კარ-ფანჯრის ლაქები — მხოლოდ ივნისში.",
      cta: "იხილე შეთავაზებები",
      link: "/sale",
      tint: "paint",
    },
    {
      id: "h2",
      kicker: "ფერი შენთვის",
      title: "შენი ფერი. შენი სივრცე.",
      sub: "24 კოლორანტი და სრული RAL პალიტრა — შეურიეთ ზუსტად ის ტონი, რომელიც გესახებათ.",
      cta: "ფერების კატალოგი",
      link: "/shop?cat=solvents",
      tint: "color",
    },
    {
      id: "h3",
      kicker: "პროფესიონალებს",
      title: "ბითუმად ფასები ობიექტებისთვის",
      sub: "ხელშეკრულება, პირადი მენეჯერი და მიწოდება ობიექტზე — მოითხოვეთ შეთავაზება.",
      cta: "მოითხოვე შეთავაზება",
      link: "/contact?type=bulk",
      tint: "pro",
    },
  ],

  promotions: [
    { id: "pr1", name: "ზაფხულის ფასდაკლება საღებავებზე", type: "pct", value: 15, target: "sobplastik-silk", from: "2026-06-01", to: "2026-06-30", active: true },
    { id: "pr2", name: "ლაქები −20%", type: "pct", value: 20, target: "lak-door", from: "2026-06-01", to: "2026-06-30", active: true },
    { id: "pr3", name: "წვრილმანი ინსტრუმენტი", type: "pct", value: 20, target: "brush-set5", from: "2026-06-05", to: "2026-07-05", active: true },
    { id: "pr4", name: "ბიტუმის მასტიკა −10%", type: "pct", value: 10, target: "hydro-bitum", from: "2026-05-20", to: "2026-06-20", active: true },
  ],

  bundles: [
    {
      id: "b1",
      name: "სამღებრო ნაკრები „ოთახი“",
      items: ["sobplastik-int", "roller-poly18", "roller-tray", "tape-masking"],
      note: "საღებავი 10კგ + ლილვაკი + კიუვეტა + მალარის ლენტი",
      price: 69.0,
      oldPrice: 78.2,
    },
    {
      id: "b2",
      name: "აბაზანის ჰერმეტიზაცია",
      items: ["hydro-cem2k", "seal-sanitary", "grout-cement"],
      note: "ჰიდროიზოლაცია 25კგ + სანიტარული სილიკონი + ფუგა 2კგ",
      price: 129.0,
      oldPrice: 140.8,
    },
    {
      id: "b3",
      name: "მონტაჟის ნაკრები „პრო“",
      items: ["foam-pro65", "tool-gun-foam", "foam-cleaner"],
      note: "ქაფი 65L + ტეფლონის პისტოლეტი + გამწმენდი",
      price: 49.0,
      oldPrice: 54.0,
    },
  ],

  /* ---------------- seed orders / inquiries ---------------- */
  orders: [
    {
      id: "MC-1042",
      type: "order",
      status: "new",
      date: "2026-06-08T14:22:00",
      customer: { name: "გიორგი მაისურაძე", phone: "+995 599 12 34 56", city: "თბილისი", address: "ვაჟა-ფშაველას 71" },
      items: [
        { pid: "sobplastik-int", size: "10კგ", color: "თეთრი", qty: 2 },
        { pid: "roller-poly18", size: "25სმ", qty: 1 },
        { pid: "tape-masking", size: "38მმ", qty: 3 },
      ],
    },
    {
      id: "MC-1041",
      type: "quote",
      status: "processing",
      date: "2026-06-08T10:05:00",
      customer: {
        name: "შპს „მშენებელი 2020“",
        phone: "+995 577 44 55 66",
        city: "ბათუმი",
        company: "შპს მშენებელი 2020",
        note: "გვჭირდება ფასადის საღებავი ~400მ² ობიექტისთვის, ივლისის დასაწყისში.",
      },
      items: [
        { pid: "sobsil-facade", size: "15ლტ", qty: 12 },
        { pid: "primer-deep", size: "10ლტ", qty: 6 },
      ],
    },
    {
      id: "MC-1040",
      type: "order",
      status: "done",
      date: "2026-06-07T16:48:00",
      customer: { name: "ნინო ბერიძე", phone: "+995 555 98 76 54", city: "თბილისი", address: "ჭავჭავაძის 24ბ" },
      items: [
        { pid: "grout-epoxy", size: "2კგ", color: "ანთრაციტი", qty: 1 },
        { pid: "seal-sanitary", size: "280მლ", color: "გამჭვირვალე", qty: 2 },
      ],
    },
    {
      id: "MC-1039",
      type: "order",
      status: "processing",
      date: "2026-06-07T11:30:00",
      customer: { name: "ლევან კვარაცხელია", phone: "+995 593 11 22 33", city: "ქუთაისი", address: "წერეთლის 88" },
      items: [
        { pid: "drill-sdsplus", size: "8×160მმ", qty: 5 },
        { pid: "bit-set32", size: "32 ცალი", qty: 1 },
        { pid: "foam-pro65", size: "850მლ", qty: 4 },
      ],
    },
    {
      id: "MC-1038",
      type: "quote",
      status: "new",
      date: "2026-06-06T09:15:00",
      customer: {
        name: "თემურ ჩხეიძე",
        phone: "+995 591 77 88 99",
        city: "რუსთავი",
        company: "ინდ. მეწარმე",
        note: "სახურავის ჰიდროიზოლაცია 250მ², მჭირდება კონსულტაციაც მასალაზე.",
      },
      items: [
        { pid: "hydro-pu", size: "25კგ", qty: 3 },
        { pid: "tape-butyl", size: "10სმ", qty: 8 },
      ],
    },
  ],
};

/* ---------------- lookups ---------------- */
export const brandById = (id: string) => MC_DATA.brands.find((b) => b.id === id);
export const catById = (id: string) => MC_DATA.categories.find((c) => c.id === id);
export const prodById = (id: string) => MC_DATA.products.find((p) => p.id === id);
export const surfName = (id: string) => {
  const s = MC_DATA.surfaces.find((x) => x.id === id);
  return s ? s.name : id;
};
